//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: copy_to_flash.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _FLASH_COPY_UI_COPY_TO_FLASH_BASE_CLASSES_HPP
#define _FLASH_COPY_UI_COPY_TO_FLASH_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class main : public wxFrame
{
protected:

protected:

public:
    main(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Copy to flash"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,250), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~main();
};

#endif
