//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: copy_to_flash.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "copy_to_flash.hpp"


// Declare the bitmap loading function
extern void wxCrafterfd8JZ6InitBitmapResources();

static bool bBitmapLoaded = false;


main::main(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterfd8JZ6InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer1 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer1);
    
    wxBoxSizer* boxSizer2 = new wxBoxSizer(wxVERTICAL);
    
    boxSizer1->Add(boxSizer2, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    SetName(wxT("main"));
    SetSize(wxDLG_UNIT(this, wxSize(500,250)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
}

main::~main()
{
}
